#!/usr/bin/env python

import alembic
import sys
from optparse import OptionParser

def main(argv=None):
    parser = alembic.options.get_option_parser()

    opts, args = parser.parse_args(argv[1:])
    if len(args) < 1:
        parser.error("no command specified") # Will exit

    command = args[0]

    alembic.main(options, file_config, command)

if __name__ == "__main__":
    main(sys.argv)

