from io import TextIOWrapper
from typing import (
    Any,
    Callable,
    Optional,
    Union,
)

def format_as_comma(value: Any) -> str: ...
def msg(msg: str, newline: bool = ..., flush: bool = ...) -> None: ...
def status(_statmsg: str, fn: Callable, *arg, **kw) -> Optional[str]: ...
def warn(msg: str, stacklevel: int = ...) -> None: ...
def write_outstream(stream: TextIOWrapper * text) -> None: ...
