from typing import Optional

def coerce_resource_to_filename(fname: str) -> str: ...
def edit(path: str): ...
def load_python_file(dir_: str, filename: str): ...
def pyc_file_from_path(path: str) -> Optional[str]: ...
def template_to_file(
    template_file: str, dest: str, output_encoding: str, **kw
) -> None: ...
